using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using BankApp.Domain.Exceptions;
using BankApp.Domain.Infrastructure;
using BankApp.Domain.ValueObjects;

namespace BankApp.Domain.Entities
{
    public class Customer : AggregateRoot // aggregate root entity
    {
        //constructor is privatized for no arguments, so that it can only be created by the repository when it is created, and not changed afterwards
        private Customer() { }
        public Customer(PersonName name, IEnumerable<Account> accounts) // constructor for creating a new customer with a list of accounts - not asking for Id as it is autogenerated by the DB
        // we do IEnumerable here so that the parameter is as open/flexible as possible (can be a collection, list, etc just anything that's enumerable), but we turn it to a list, then ReadOnlyCollection later to make it as clear and exact as possible what will be returned
        {
            Name = name;
            //_accounts = accounts?.ToList() ?? new List<Account>(); // keeps it more open to nullability, but not necessary, and if we want to add this later it won't break anything, however if we do this now and then decide later to not allow it to be nullable, reversing that would cause issues
            _accounts = accounts.ToList(); // IMPORTANT PRINCIPLE this decision could go either way, but you really only want things to be nullable if you have a business case where it means something for this to be null
                                            // also if we did one day have a customer that didn't need to have an account, it may make more sense to make a separate type of customer that doesn't have accounts
                                                // per subdomain notes, we might have a subdomain for banking customers, and one for business customers .. some may be both and we'd figure out logic to combine, but overall the customer here that has to have accounts is in one subdomain for banking customers
        }



        public int Id { get; private set; } // change this to private set so it can only be set by the repository when it is created, and not changed afterwards
        
        public PersonName Name {get; private set; } 

        private List<Account> _accounts = new List<Account>(); // initialize the list to an empty list so it is never null
        // shorthand for new List<Account>() is just = [];
        public IReadOnlyList<Account> Accounts => _accounts.AsReadOnly(); // can only get the _accounts list, not set it, except by methods within this class 
        // changed from ReadOnlyCollection to IReadOnlyList
        public void MakeDeposit(int accountId, Money amount)
        {
            // enforce deposit amount: could also do this in Account Deposit method
            if (amount <= 0)
            {
                throw new ArgumentException("Deposit amount must be greater than zero.", nameof(amount));
            } // else if (amount * 100 != Math.Floor(amount * 100)) // to enforce 2 decimal places, we will check if the amount multiplied by 100 is an integer, which means it has at most 2 decimal places, since anything more than 2 decimal places would result in a non-integer when multiplied by 100
            // { 
            //     throw new ArgumentException("Deposit amount must have at most 2 decimal places.", nameof(amount));
            // }
            // maybe move this to a separate validation method, and tehn we could use it in withdrawal as well, and any other place where we need to validate an amount, so that we don't have to repeat this logic in multiple places
              // moved this to Money valueobject for validation - not enforcing the greater than 0 in the value object though because withdrawals and balances can be negative
            

            // var account = _accounts.FirstOrDefault(a => a.Id == accountId); // going to be doing this a lot, so could be better later on to put this in its own private in class or public global method for FindAccount, FindAccountById, FIndAccount with a fed query instead of specific byId,etc...  or something like that
            // if (account == null) // or account is null
            // {
            //     throw new KeyNotFoundException($"Account with Id {accountId} not found for customer with Id {Id}.");
            // }
            var account = FindAccount(accountId); // per above, we created the private method to do this without repeat code
            account.Deposit(amount); // this will call the Deposit method in the account class, which will update the balance
        }

        public void MakeWithdrawal(int accountId, Money amount)
        {
            if (amount <= 0)
            {
                throw new ArgumentException("Withdrawal amount must be greater than zero.", nameof(amount));
            } 
            var account = FindAccount(accountId); 

            if (account.Balance - amount < 0) // enforce that the withdrawal amount cannot be greater than the balance, so that we don't allow overdrafts - this is a business rule that we want to enforce in the domain layer, because it is a rule that is specific to our business/domain, and not a general technical concern, so it belongs in the domain layer rather than the API layer
            {
                throw new DomainException($"Withdrawal amount of {amount} exceeds the current balance of {account.Balance} for account with Id {accountId}.");
            } // {amount} automatically calls ToString on Money type to display the amount in the error message

            account.Withdraw(amount); 
        }

        public Money GetAccountBalance(int accountId)
        {
            var account = FindAccount(accountId);
            return account.Balance;
        }

        // put this method in here instead of account class because it is more of a customer concern than an account concern
        private Account FindAccount(int accountId)
        {
            var account = _accounts.FirstOrDefault(a => a.Id == accountId);
            if (account is null)
            {
                throw new KeyNotFoundException($"Account with Id {accountId} not found for customer with Id {Id}.");
            }
            return account;
        }
    }
}