using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using BankApp.Domain.Infrastructure;

namespace BankApp.Domain.Entities
{
    public class Customer : AggregateRoot // aggregate root entity
    {
        //constructor is privatized for no arguments, so that it can only be created by the repository when it is created, and not changed afterwards
        private Customer() { }
        public Customer(IEnumerable<Account> accounts) // constructor for creating a new customer with a list of accounts - not asking for Id as it is autogenerated by the DB
        // we do IEnumerable here so that the parameter is as open/flexible as possible (can be a collection, list, etc just anything that's enumerable), but we turn it to a list, then ReadOnlyCollection later to make it as clear and exact as possible what will be returned
        {
            //_accounts = accounts?.ToList() ?? new List<Account>(); // keeps it more open to nullability, but not necessary, and if we want to add this later it won't break anything, however if we do this now and then decide later to not allow it to be nullable, reversing that would cause issues
            _accounts = accounts.ToList(); // IMPORTANT PRINCIPLE this decision could go either way, but you really only want things to be nullable if you have a business case where it means something for this to be null
                                            // also if we did one day have a customer that didn't need to have an account, it may make more sense to make a separate type of customer that doesn't have accounts
                                                // per subdomain notes, we might have a subdomain for banking customers, and one for business customers .. some may be both and we'd figure out logic to combine, but overall the customer here that has to have accounts is in one subdomain for banking customers
        }



        public int Id { get; private set; } // change this to private set so it can only be set by the repository when it is created, and not changed afterwards
        
        private List<Account> _accounts = new List<Account>(); // initialize the list to an empty list so it is never null
        // shorthand for new List<Account>() is just = [];
        public ReadOnlyCollection<Account> Accounts => _accounts.AsReadOnly(); // can only get the _accounts list, not set it, except by methods within this class 
    }
}